### ISSUE TITLE
magit-item-highlight masks the diff +/- colors

### ISSUE THREAD

**Issue by tomjakubowski** [jordonbiondo/ample-theme#11]
![2015-05-21-140102_692x222_scrot](https://cloud.githubusercontent.com/assets/667901/7758882/e8336b6c-ffc1-11e4-893e-9f90a4d1ae2c.png)

There are three chunks there: the second one is currently highlighted but the nice font lock changes for the addition/deletions, which are present in the unhighlighted chunks, are missing. 

See a related magit issue: https://github.com/magit/magit/issues/133

**Comment by tomjakubowski** [comment]
OK, I think that magit issue isn't actually related :-). I guess the problem is that the whole hunk is rendered with that `ample/region` background color, which does make sense, but then there's no way to distinguish additions/deletions/non-changes colorwise.

**Comment by jordonbiondo** [comment]
Is this the same issue you are talking about? This came up recently on stack exchange.

http://emacs.stackexchange.com/questions/10975/customize-face-magit-item-highlight-properly/12323#12323

If so, maybe my solution on that question can help you.

**Comment by jordonbiondo** [comment]
Does this happen with every hunk you highlight? For instance if you were in the state that screenshot shows and you pressed `p` to move to the top hunk, does the green go away? I can't seem to reproduce what is shown in the screenshot.

What version of magit are you running?

**Comment by tomjakubowski** [comment]
thanks!
