### ISSUE TITLE
Highlighting current region?

### ISSUE THREAD

**Issue by ZucchiniZe** [jordonbiondo/ample-theme#13]
First of all, I **love** this theme very much and have been using it for 2 months now but for some reason the current region (I think, still pretty new to emacs) in a light green color which makes it hard to read the text I am typing, I have tested this out in other themes and it seems like it is only this theme that does it. If it is any use I use spacemacs and can give you my current config if needed.

**Comment by jordonbiondo** [comment]
Can you provide a screen shot?

**Comment by ZucchiniZe** [comment]
I am using `ample` with GUI emacs and here is a screenshot demoing the problem ![](http://i.imgur.com/Z7IVCaJ.png)

**Comment by jordonbiondo** [comment]
That color must be coming from somewhere else in your config, I can try helping you find it if you post your config. 

What are the properties of the `region` face when you use `describe-face`?

**Comment by jordonbiondo** [comment]
It is also possible that you have more than one theme enabled. You can use `disable-theme` to see completions of currently enabled themes.

**Comment by ZucchiniZe** [comment]
Here is my config https://github.com/ZucchiniZe/dotfiles/blob/master/spacemacs and it does look like I have something enabled in my region face https://gist.github.com/ZucchiniZe/898c4a35670c2684bf7d

**Comment by jordonbiondo** [comment]
if you disable `spacemacs-light` does it fix the issue?

**Comment by jordonbiondo** [comment]
@ZucchiniZe were you ever able to resolve this issue?

**Comment by ZucchiniZe** [comment]
Sadly not, it still persists.

**Comment by jordonbiondo** [comment]
From everything I can tell this must be related to something else in your config and not coming from ample theme itself so I am closing this.
