### ISSUE TITLE
Yellow for both variable names and strings?

### ISSUE THREAD

**Issue by aldanor** [jordonbiondo/ample-theme#14]
Here's a small Python example using default ample:

![image](https://cloud.githubusercontent.com/assets/2418513/13315883/490065ac-dba5-11e5-8c7c-87d307a47522.png)

If you squint hard _enough_, you may notice the strings are actually of different colour :smile: 

`ample/yellow` and `ample/tan` are almost the same color, which makes it basically impossible to  distinguish variables from strings colorwise. Wonder if one of the two colors should be changed to improve general readability?

// Thanks for otherwise great theme!

**Comment by jordonbiondo** [comment]
I agree they are a bit close to each other, but at this point, I think it's too late to go about changing the core colors of the theme with as many people using it as I think there might be.

Though if you have a suggestion for one of the colors I would be willing to considerate it.

If you'd like to change the color of strings or variables just for yourself you can use something like this:


```lisp
(with-eval-after-load "ample-theme"
  (custom-theme-set-faces
   'ample
   '(font-lock-string-face ((t (:foreground "#bdba81"))))))
```

The color provided in that code is "more tan" than the original, you see the difference here: 
The new is on the left, and the old is on the right.
<img width="363" alt="screen shot 2016-02-25 at 9 00 49 am" src="https://cloud.githubusercontent.com/assets/1441728/13321642/5288a5d2-db9e-11e5-840d-26d975663742.png">

Here it is in code:
<img width="192" alt="screen shot 2016-02-25 at 8 56 53 am" src="https://cloud.githubusercontent.com/assets/1441728/13321682/789ea56e-db9e-11e5-9942-37f5e7417a51.png">

**Comment by aldanor** [comment]
@jordonbiondo Thanks for replying! I'd like to try slight variations to string/variable colors to see what works but the `with-eval-after-load` snippet doesn't work somewhy (when placed in `dotspacemacs/user-config()`, I'm using Spacemacs), wonder why.

IMO variables should be quite close in style to normal text (or same, as in oceanic-next) but easily discernible from it. In any case, it's always good to have them differ from strings which is especially important in languages like JS or Python where you quite often have a mix of both on the screen...

**Comment by sooheon** [comment]
I have a similar issue with `ample/green` (#a9df90) and `ample/yellow` ("#aaca86") of `ample-flat`. I really think these can be differentiated more. `with-eval-after-load` is not a solution, imo. There are 23 occurrences of `ample/yellow` in ample-flat-theme.el, and a eval-after-load hook to configure each of these is... difficult. 

I actually see that `ample/bright-yellow` (#caca86) is only used once, for the minibuffer prompt. It has a nice contrast to `ample/green`. What do you think about merging the two into one, and letting all current references to `ample/yellow` take the #caca86 color?

### How ample/green and ample/yellow (org heading 1 and 2) look:
<img width="676" alt="screen shot 2016-03-03 at 5 27 08 pm" src="https://cloud.githubusercontent.com/assets/302945/13488552/4a77fa38-e165-11e5-91af-67b6cf51dd75.png">

### ample colors

**Comment by aldanor** [comment]
@sooheon Agreed, that would be a reasonable change and would help python-mode as well

**Comment by aldanor** [comment]
@jordonbiondo @sooheon I've experimented a little with the built-in colors re: string color face. Aside from `magit` which doesn't really clash with anything, `ample/dark-green` is only used for `js2-private-function-call` which is unused (https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L1048) and for `js2-function-param`. So this is *one* specific case in *one* specific mode as opposed to strings that exist pretty much everywhere. In fact, `js2-function-param` can be safely canged to `ample/yellow` to be consistent with how it's highlighted in most other modes. Here's examples in Rust and in JS.

**Before**

`js2-mode`: (note that object properties are not highlighted at all by the way)
![image](https://cloud.githubusercontent.com/assets/2418513/13898475/d60a6b2e-edc9-11e5-9e80-f86191cd0c13.png)

`rust-mode`:
![image](https://cloud.githubusercontent.com/assets/2418513/13898476/e8451906-edc9-11e5-89bf-ab1e34c88d79.png)

**After**

Changes:

```
font-lock-string-face = ample/dark-green
js2-function-param = ample/yellow
js2-object-property = ample/orange
```

`js2-mode`:
![image](https://cloud.githubusercontent.com/assets/2418513/13898491/721216ca-edca-11e5-864f-0f2ce806767d.png)

`rust-mode`:
![image](https://cloud.githubusercontent.com/assets/2418513/13898492/7f5ac4a8-edca-11e5-862c-74ec6b1c72c9.png)

**Comment by jordonbiondo** [comment]
I am working on providing a means of overriding all the colors in the themes which should cover most use cases.

If you want to override the colors you would do something like this:

```lisp
(ample-theme-with-overrides ((ample/yellow "abab9f") (ample/blue "3f3f9f"))
   (ample-theme-define))
```
This should cover most use cases. 

@aldanor I'm a little hesitant to change the `js2-function-param` face because I am an everyday ample-theme user and an every day `js2-mode` user. As such I have become very reliant on that dark green color as a means to pick out arrow functions and specifically promise `.then` calls in code. I'm going to try out the change to yellow for a bit and see if the transition is not too painful.

**Comment by jordonbiondo** [comment]
https://github.com/jordonbiondo/ample-theme#easy-customization
