### ISSUE TITLE
Clashing AUCTeX faces

### ISSUE THREAD

**Issue by fice-t** [jordonbiondo/ample-theme#15]
I really like this theme, but there's a couple of issues with the AUCTeX faces:

1) `font-lock-constant-face` and `font-latex-math-face` share the same colour.

2) `font-lock-comment-face`, `font-latex-sedate-face`, `font-latex-italic-face`, and `font-latex-bold-face` share the same colour.

In the default Emacs theme, none of these (besides bold/italic) share the same colour.

I don't really mind the first, but the second is annoying (particularly the sedate face).
Unfortunately I haven't figured out a suitable change.

@justbur I see you put the AUCTeX faces in. Do you have any ideas?

**Comment by justbur** [comment]
No sorry. I didn't spend time trying to perfect it. I just took a stab at something reasonable that got away from ugly auctex defaults. I wouldn't mind further improvements.

**Comment by jordonbiondo** [comment]
If either of you would like to submit a PR for improvements that would be great. I don't use auctex myself so before/after screenshots would be ideal.

**Comment by fice-t** [comment]
It turns out that few other themes I checked out that implemented the faces didn't let the math face have its own colour, so I guess that can be ignored.

I'm not sure what to do about `font-latex-sedate-face` though. It should probably be a darker colour (as per the name), but I can't find a fitting new one that's already defined in the theme. Perhaps a new colour should be introduced -- a brown or another blue?

Here's before:
![grey](https://cloud.githubusercontent.com/assets/13156601/14591259/3ff9a0fa-04cb-11e6-9d33-f46a17cf2a91.png)

Brown:
![brown](https://cloud.githubusercontent.com/assets/13156601/14591261/507f6234-04cb-11e6-87bd-93fc80d4c2aa.png)

(new) Blue:
![blue](https://cloud.githubusercontent.com/assets/13156601/14591279/a93ad606-04cb-11e6-96b4-8a156a8b1f35.png)

Any suggestions? I'm not very good at choosing new colours.

**Comment by jordonbiondo** [comment]
I'm partial to the brown in those screenshots, what color is that? I think it looks good with the theme.

**Comment by fice-t** [comment]
It's the conveniently named #987654. At least in the default ample I think it looks nice too.

**Comment by fice-t** [comment]
@jordonbiondo I finally got around to making a PR for this with the above brown and a few other changes.

**Comment by jordonbiondo** [comment]
Thanks!
