### ISSUE TITLE
top color is very strange

### ISSUE THREAD

**Issue by zsaw** [jordonbiondo/ample-theme#33]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/56421950/233514237-7a73e156-ef81-47fe-88f3-ad83bdcd73f8.png">

top color is very strange

**Comment by zsaw** [comment]
header-line

**Comment by jordonbiondo** [comment]
No LSP specific faces are specified in the theme.

I will probably add lsp faces at some point.

**Comment by jordonbiondo** [comment]
@zsaw I added specs for lsp headerline faces in https://github.com/jordonbiondo/ample-theme/commit/39ac29cf9a1229bb076964335fbd71cfb52e498b

It's not meant to be final, it's very basic and the goal was just to make lsp headers readable.
