### ISSUE TITLE
Incorrect work with powerline

### ISSUE THREAD

**Issue by punzik** [jordonbiondo/ample-theme#6]
Ample theme:
![bad](https://cloud.githubusercontent.com/assets/1275083/6413978/59c41366-bea5-11e4-8261-c2b6c947b0ac.png)

Another theme:
![good](https://cloud.githubusercontent.com/assets/1275083/6413977/59c28b40-bea5-11e4-88b3-999d6a7efcd9.png)

**Comment by jordonbiondo** [comment]
Thanks for pointing that out, I do not use powerline anymore so it has gone unnoticed. I saw you forked the theme, i'd be happy to merge a PR in that fixes the issue, else I'll get to it when I can.

**Comment by punzik** [comment]
I will try to fix this bug, but my knowledge of elisp is not very good. If I can fix it I'll send changes to you necessarily.

**Comment by jordonbiondo** [comment]
@punzik can you confirm whether or not power line displays appropriately now?

**Comment by punzik** [comment]
Work fine! Thanks!
